local IVEngineClient = utils.find_interface("engine.dll", "VEngineClient014") or error("Engine client is invalid")
local IVEngineClientPtr = ffi.cast("void***", IVEngineClient)

local English = {
    "The only thing lower than your k/d ratio is your I.Q.",
    "Your aim is so poor that people held a fundraiser for it",
    "Better buy PC, stop playing at school library",
    "The only thing more unreliable than you is the condom your dad used.",
    "Calling you a retard is a compliment in comparison to how stupid you actually are.",
    "I didnt know dying was a special ability.",
    "If I jumped from your ego to your intelligence, Id die of starvation half-way down.",
    "Studies show that aiming gives you better chances of hitting your target.",
    "You should let your chair play, at least it knows how to support.",
    "There are about 37 trillion cells working together in your body right now, and you are disappointing every single one of them.",
    "I'd call you a tool, but that would imply you were useful in at least one way.",
    "Youre the human equivalent of a participation award.",
    "I'd love to see things from your perspective, but I dont think I could shove my head that far up my ass.",
    "I'm not trash talking, Im talking to trash",
    "Legend has it that the number 0 was first invented after scientists calculated your chance of doing something useful.",
    "You're the type of player to get 3rd place in a 1v1 match",
    "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
    "You're an inspiration for birth control.",
    "Does your ass ever get jealous of the amount of shit that comes out of your mouth",
    "You should turn the game off. Just walk outside and find the nearest tree, then apologise to it for wasting so much oxygen.",
    "I'd tell you to shoot yourself, but I bet youd miss",
    "Did you know sharks only kill 5 people each year? Looks like you got some competition",
    "Some babies were dropped on their heads but you were clearly thrown at a wall",
    "To which foundation do I need to donate to help you?",
    "I'm sure your bodypillow is very proud of you.",
    "Two wrongs dont make a right, take your parents as an example.",
    "I bet the last time u felt a breast was in a kfc bucket",
    "Maybe God made you a bit too special.",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "It must be difficult for you, exhausting your entire vocabulary in one sentence.",
    "You have some big balls on you. Too bad they belong to the guy fucking you from behind.",
    "If only you could hit an enemy as much as your dad hits you.",
    "I'm surprised that you were able hit the Install button",
    "Some people get paid to suck, you do it for free.",
    "I would ask you how old you are but I know you can't count that high.",
    "I'm okay with this team. I work in the city as a garbage collector. I'm used to carrying trash.",
    "You're as dense as a brick, but honestly a less useful one.",
    "I'd call you cancer, but at least cancer gets kills",
    "Who set the bots to passive?",
    "You're the reason abortion was legalized"
}
local Russian = {
    "ты понимаешь что я на чердаке твою бабулю повесил своим хуем",
    "ты понимаешь что я об лобок твоей маамшки своим хуем орехи колю",
    "мать твоя стонет под скрипы гитары от моего хуя",
    "мне твою щеку что ли потереть как люстру?",
    "слышь, твой рот мне же говорил что ты проститутка влиятельной колхозницы",
    "почему ты прячешь мой хуй у себя во рту, любишь чтоле?",
    "когда твоя мамаша моим хуем играет в настольные игры, ты зачем мне хуй сосешь?",
    "я могу ебать твою мать на неведомом отстрове",
    "давай из твоего лица вырежим кусочек кожи и сделаем из него призерватив?",
    "ты заебал мне всасывать, ядобью твой рот до конца ты будешь умолять что бы я тад тебе сосать",
    "твоя мамаша когда сдохла хули ты мне в хуй ныл?",
    "ебал твою мать в жопу пока ты мне хуй сосал",
    "сын собаки слышь долбанутая иди отсюда и мамку свою прихвати",
    "когда твой папа стал раком русский охотник выстрелил ему в анал с ружья приняв его за лося",
    "ты понимаешь что я выбил своим хуем гланды твоей мамашки?",
    "слыш) бревно ты ебаное) мамашу твою на сеновале ебал",
    "я твою мамашу пас своим хуем на майдане",
    "ты понимаешь что я щас своим хуем через пиздак твоей мамашки буду торговые пути проводить",
    "я пиздой твоей матери вкрутил лампочку",
    "я ща через свой хуй пущу электро заряд тебе в мозг",
    "пидор огнедыщащий иди сюда я тебя ебать буду",
    "нахуй ты проводил тест драйв на моем хуе",
    "твоя мать на моем хуе ездит покупать моему хую украшения",
    "твоя мать зачем хвастается моим хуем перед подружками",
    "твоя мать вместо подушки ставит мой хуй себе под голову и так спит",
    "твоя мать моим хуем убила сталина",
    "твоя мать моим хуем умеет останавливать пули",
    "твоя мать когда играет в бадминтон вместо ракетки использует мой хуй",
    "твоя мать когда выпила мою сперму у неё крыша поехала и она начала танцевать русскую чечетку",
    "моя сперма такая дрогоценая что твоя мать её наливает в баночки и начинает ей молится",
    "твоя мать мою сперму пила как водку",
    "твоя мать увидела на витрине мой хуй и каждый раз когда отец твоей матери не давал она брала мой хуй и ебала себя",
    "давай я твою мать поебу на касписком море и буду подпевать песню каспийский груз",
    "твоя мать стирала тебе одежду моей спермой",
    "твоя мать построила одежный завод в виде моего хуя",
    "зачем твоя мать на моем хуе поставила светильник ?",
    "ты когда просил борщ со сметаной твоя мать приносила борщ с моей спермой и ты даже замечал",
    "я на пизде твоей матери устраивал скачки на конях",
    "я тебе ша глаз протикну своим хуем как шампур шашлык",
    "твоя мать когда готовит торт всегда добавляет 10 милиграм моей спермы",
    "мой хуй посадил яблоню на пизде твоей матеи",
    "мой хуй построил кондитерскую фабрику",    
}
local Arabic = {
    "هل تفهم أنني علقت جدتك في العلية بقضيبي",
    "هل تفهم أنني تكسير المكسرات على العانة أمك مع ديك بلدي",
    "أمك تشتكي تحت صرير الغيتار من قضيبي",
    "يجب أن فرك خدك مثل الثريا?",
    "مهلا ، فمك هو نفسه بالنسبة لي قال أنك عاهرة لمزارع جماعي مؤثر",
    "لماذا إخفاء ديك بلدي في فمك, هل تحب شيئا?",
    "عندما يلعب أمك ألعاب الطاولة مع ديك بلدي, لماذا تمتص ديك بلدي?",
    "يمكنني مضاجعة والدتك في شبه جزيرة مجهولة",
    "دعونا قطع من وجهك قطعة من الجلد وجعل الواقي الذكري للخروج منه?",
    "لقد مارست الجنس معي ، سأسمم فمك حتى النهاية، سوف تتوسل إلي أن أمتصك",
    "أمك عندما ماتت, هل يمارس الجنس معي في ديك?",
    "مارس الجنس أمك في الحمار بينما كنت امتص ديك بلدي",
    "ابن كلب ، أيها الوغد ، اخرج من هنا وأمسك بأمك",
    "عندما أصيب والدك بالسرطان ، أطلق عليه صياد روسي النار في الشرج بمسدس ، ظنا منه أنه إلك",
    "هل تفهم أنني طرقت اللوزتين والدتك مع ديك بلدي?",
    "هل تسمع) أنت سخيف سجل) مارس الجنس أمك في هايلوفت",
    "أمرر أمك بقضيبي على الميدان",
    "أنت تفهم أنه الآن سأقوم بإجراء طرق التجارة مع قضيبي من خلال مهبل والدتك،",
    "أنا ثمل المصباح الكهربائي في العضو التناسلي النسوي والدتك،",
    "سأضع شحنة كهربائية في دماغك من خلال قضيبي",
    "شاذ يأكل النار ، تعال إلى هنا سأضاجعك،",
    "اللعنة عليك ، لقد أجريت تجربة قيادة على اللعنة",
    "أمك تركب قضيبي لشراء مجوهرات لقضيبي",
    "لماذا أمك التباهي ديك بلدي أمام صديقاتها",
    "أمك تضع قضيبي تحت رأسها بدلا من الوسادة وتنام هكذا",
    "أمك قتلت ستالين بقضيبي",
    "أمك تعرف كيف توقف الرصاص بقضيبي",
    "أمك عندما تلعب كرة الريشة تستخدم قضيبي بدلا من المضرب",
    "أمك عندما شربت حيواني المنوي ، أصيبت بالجنون وبدأت ترقص رقص الصنبور الروسي",
    "حيواناتي المنوية ثمينة جدا لدرجة أن والدتك تصبها في الجرار وتبدأ في الصلاة لها",
    "أمك شربت الحيوانات المنوية مثل الفودكا",
    "رأت والدتك قضيبي في النافذة وفي كل مرة لم يسمح لها والد والدتك ، أخذت قضيبي ومارست الجنس مع نفسها",
    "اسمحوا لي أن يمارس الجنس مع والدتك على بحر قزوين والغناء على طول لأغنية بحر قزوين البضائع",
    "أمك غسلت ملابسك بحيواني المنوية",
    "أمك بنت مصنع ملابس على شكل قضيبي",
    "لماذا وضعت والدتك مصباح على ديك بلدي?",
    "عندما طلبت البرش مع القشدة الحامضة ، أحضرت والدتك البرش مع الحيوانات المنوية الخاصة بي وحتى لاحظت",
    "لقد رتبت سباقات الخيول على كس والدتك",
    "أنا شا لك سوف فرك عيني مع ديك بلدي مثل سيخ الشواء",
    "تضيف والدتك دائما 10 ملليغرام من الحيوانات المنوية عندما تطبخ كعكة",
    "ديك بلدي زرعت شجرة تفاح على كس والدتك",
    "ديك بلدي بنى مصنع الحلويات",
    "﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽"
}
local Spanish = {
    "Lo único más bajo que tu relación k/d es tu coeficiente intelectual",
    "Tu objetivo es tan pobre que la gente organizar una recaudación de fondos para ello",
    "Mejor compra PC, deja de jugar en la biblioteca de la escuela",
    "Lo único menos confiable que tú es el condón que usó tu papá",
    "Llamarte retrasado es un cumplido en comparación con lo estúpido que eres en realidad",
    "No sabía que morir era una habilidad especial.",
    "Si saltara de tu ego a tu inteligencia, me moriría de hambre a mitad de camino",
    "Los estudios demuestran que apuntar te da mejores posibilidades de acertar en tu objetivo",
    "Deberías dejar que tu silla juegue, por lo menos sabe apoyar",
    "Hay alrededor de 37 billones de células trabajando juntas en tu cuerpo en este momento, y estás decepcionando a cada una de ellas",
    "Te llamaría una herramienta, pero eso implicaría que fuiste útil al menos de una manera",
    "Eres el equivalente humano de un premio de participación.",
    "Me encantaría ver las cosas desde tu perspectiva, pero no creo que pueda meter mi cabeza tan adentro de mi trasero",
    "No estoy hablando basura, estoy hablando con basura",
    "Cuenta la leyenda que el número 0 se inventó por primera vez después de que los científicos calcularan tus posibilidades de hacer algo útil",
    "Eres el tipo de jugador que obtiene el 3er lugar en un partido 1v1",
    "No digo que te odie, pero desconectaría tu soporte vital para cargar mi teléfono",
    "Eres una inspiración para el control de la natalidad.",
    "¿Tu trasero alguna vez se pone celoso de la cantidad de mierda que sale de tu boca?",
    "Deberías apagar el juego. Solo camina afuera y encuentra el árbol más cercano, luego discúlpate por desperdiciar tanto oxígeno",
    "Te diría que te dispararas, pero apuesto a que fallarías",
    "¿Sabías que los tiburones solo matan a 5 personas cada año? Parece que tienes algo de competencia",
    "Algunos bebés se tiraron de cabeza, pero a ti claramente te arrojaron contra una pared",
    "¿A qué fundación tengo que donar para ayudarte?",
    "Seguro que tu almohada está muy orgullosa de ti.",
    "Dos errores no hacen un acierto, toma a tus padres como ejemplo",
    "Apuesto a que la última vez que sentiste un seno fue en un balde de KFC",
    "Tal vez Dios te hizo un poco demasiado especial.",
    "Apuesto a que tu cerebro se siente como nuevo, ya que nunca lo usas",
    "Debe ser difícil para ti, agotar todo tu vocabulario en una oración.",
    "Tienes unas pelotas grandes. Lástima que pertenecen al tipo que te folla por detrás",
    "Si tan solo pudieras golpear a un enemigo tanto como tu padre te golpea a ti",
    "Me sorprende que hayas podido presionar el botón Instalar",
    "A algunas personas les pagan por chupar, tú lo haces gratis",
    "Te preguntaría cuántos años tienes, pero sé que no puedes contar tanto",
    "Estoy bien con este equipo. Trabajo en la ciudad como recolector de basura. Estoy acostumbrado a cargar basura",
    "Eres tan denso como un ladrillo, pero honestamente uno menos útil",
    "Te llamaría cáncer, pero al menos el cáncer mata",
    "¿Quién puso los bots en pasivo?",
    "Tú eres la razón por la que se legalizó el aborto"
}
local Polish = {
    "Jedyną rzeczą, która jest niższa od twojego współczynnika k/d, jest twoje I.Q.",
    "Twój cel jest tak słaby, że ludzie zorganizowali na niego zbiórkę pieniędzy",
    "Lepiej kup komputer, przestań grać w szkolnej bibliotece",
    "Jedyną rzeczą bardziej zawodną od ciebie jest prezerwatywa, której używał twój tata.",
    "Nazywanie cię debilem to komplement w porównaniu do tego, jak głupi jesteś w rzeczywistości.",
    "Nie wiedziałem, że umieranie to specjalna umiejętność.",
    "Gdybym przeskoczył z twojego ego do twojej inteligencji, umarłbym z głodu w połowie drogi.",
    "Badania pokazują, że celowanie daje większe szanse na trafienie w cel.",
    "Powinieneś pozwolić swojemu krzesłu grać, przynajmniej wie, jak je wspierać.",
    "W twoim ciele jest teraz około 37 bilionów komórek współpracujących ze sobą i rozczarowujesz każdą z nich.",
    "Nazwałbym cię narzędziem, ale to by sugerowało, że byłeś przydatny przynajmniej w jeden sposób.",
    "Jesteś ludzkim odpowiednikiem nagrody za uczestnictwo.",
    "Chciałabym zobaczyć rzeczy z twojej perspektywy, ale nie sądzę, żebym mogła wsadzić głowę tak wysoko w dupę.",
    "Nie gadam śmieci, gadam do śmieci",
    "Legenda głosi, że liczba 0 została wynaleziona po raz pierwszy po tym, jak naukowcy obliczyli Twoje szanse na zrobienie czegoś pożytecznego.",
    "Jesteś typem gracza, który zajmuje 3 miejsce w meczu 1 na 1",
    "Nie mówię, że cię nienawidzę, ale odłączyłbym twoje podtrzymywanie życia, aby naładować mój telefon.",
    "Jesteś inspiracją do kontroli urodzeń.",
    "Czy twój tyłek kiedykolwiek zazdrości ci ilości gówna, które wychodzi z twoich ust",
    "Powinieneś wyłączyć grę. Po prostu wyjdź na zewnątrz i znajdź najbliższe drzewo, a następnie przeproś je za zmarnowanie tak dużej ilości tlenu.",
    "Powiedziałbym, żebyś się zastrzelił, ale założę się, że chybisz",
    "Czy wiesz, że rekiny zabijają tylko 5 osób rocznie? Wygląda na to, że masz jakąś konkurencję",
    "Niektóre dzieci zostały upuszczone na głowy, ale ty wyraźnie rzuciłeś o ścianę",
    "Na jaką fundację muszę przekazać darowiznę, aby Ci pomóc?",
    "Jestem pewien, że twoja poduszka do ciała jest z ciebie bardzo dumna.",
    "Dwa zło nie czynią dobra, weźmy przykład swoich rodziców.",
    "Założę się, że ostatnim razem czułeś, że pierś była w wiadrze KFC",
    "Może Bóg uczynił cię trochę zbyt wyjątkowym.",
    "Założę się, że twój mózg czuje się jak nowy, widząc, że nigdy go nie używasz.",
    "To musi być dla ciebie trudne, wyczerpując całe twoje słownictwo w jednym zdaniu.",
    "Masz przy sobie duże jaja. Szkoda, że ​​należą do faceta pieprzącego cię od tyłu.",
    "Gdybyś tylko mógł uderzyć wroga tak mocno, jak twój tata uderza ciebie.",
    "Jestem zaskoczony, że udało Ci się nacisnąć przycisk Instaluj",
    "Niektórzy ludzie płacą za ssanie, robisz to za darmo.",
    "Chciałbym zapytać, ile masz lat, ale wiem, że nie możesz liczyć tak wysoko.",
    "Jestem w porządku z tym zespołem. Pracuję w mieście jako śmieciarz. Przywykłem do noszenia śmieci.",
    "Jesteś gęsty jak cegła, ale szczerze mówiąc mniej użyteczny.",
    "Nazwałbym cię rakiem, ale przynajmniej rak zabija",
    "Kto ustawił boty w tryb pasywny?",
    "Jesteś powodem, dla którego aborcja została zalegalizowana"
}
local Bulgarian = {
    "Единственото нещо, което е по-ниско от вашето съотношение k/d, е вашият I.Q",
    "Целта ви е толкова лоша, че хората организираха набиране на средства за не",
    "По-добре си купете компютър, спрете да играете в училищната библиотек",
    "Единственото нещо, което е по-ненадеждно от теб, е презервативът, който баща ти е използвал",
    "Да те нарека изостанал е комплимент в сравнение с това колко глупав си всъщност",
    "Не знаех, че умирането е специална способност",
    "Ако скоча от твоето его към твоята интелигентност, ще умра от глад наполовина",
    "Проучванията показват, че прицелването ви дава по-добри шансове да уцелите целта си",
    "Трябва да оставите стола си да играе, той поне знае как да поддържа",
    "Има около 37 трилиона клетки, които работят заедно в тялото ви в момента и вие разочаровате всяка една от тях",
    "Бих ви нарекъл инструмент, но това би означавало, че сте били полезни поне по един начин",
    "Вие сте човешкият еквивалент на награда за участие",
    "Бих искал да видя нещата от твоята гледна точка, но не мисля, че бих могъл да си пъхна главата толкова навътре в задника",
    "Аз не говоря боклук, говоря на боклу",
    "Легендата гласи, че числото 0 е измислено за първи път, след като учените са изчислили шанса ви да направите нещо полезно",
    "Вие сте от типа играч, който печели 3-то място в мач 1 срещу ",
    "Не казвам, че те мразя, но бих изключил захранването ти, за да заредя телефона си",
    "Вие сте вдъхновение за контрол на раждаемостта",
    "Задникът ти завижда ли някога от количеството глупости, които излизат от устата т",
    "Трябва да изключите играта. Просто излезте навън и намерете най-близкото дърво, след което му се извинете, че губите толкова много кислород",
    "Бих ти казал да се застреляш, но се обзалагам, че ще пропусне",
    "Знаете ли, че акулите убиват само 5 души всяка година? Изглежда, че имате конкуренци",
    "Някои бебета бяха изпуснати на главите си, но вие явно бяхте хвърлени в стенат",
    "На коя фондация трябва да даря, за да ви помогна",
    "Сигурен съм, че вашата възглавница много се гордее с вас",
    "Две грешки не правят едно правилно, вземете родителите си за приме",
    "Обзалагам се, че последният път, когато усетихте гърди, беше в кофа на KF",
    "Може би Бог те е направил твърде специален",
    "Обзалагам се, че мозъкът ви се чувства като нов, като виждате, че никога не го използвате",
    "Сигурно ви е трудно да изчерпвате целия си речник в едно изречение",
    "Имаш големи топки по себе си. Жалко, че принадлежат на човека, който те чука отзад",
    "Само ако можеше да удряш враг толкова, колкото баща ти удря теб",
    "Изненадан съм, че успяхте да натиснете бутона Инсталиран",
    "На някои хора им плащат да сучат, вие го правите безплатно",
    "Бих те попитал на колко години си, но знам, че не можеш да броиш толкова високо",
    "Добре съм с този екип. Работя в града като сметосъбирач. Свикнал съм да нося боклук",
    "Ти си плътен като тухла, но честно казано си по-малко полезен",
    "Бих те нарекъл рак, но поне ракът убив",
    "Кой постави ботовете на пасивни",
    "Ти си причината абортите да бъдат легализирани"
}
local Hungarian = {
    "Az egyetlen dolog, ami alacsonyabb a k/d aránynál, az az I.Q.",
    "Olyan rossz a célod, hogy az emberek adománygyűjtést tartottak érte",
    "Jobb, ha vásárolsz PC-t, ne játssz az iskolai könyvtárban",
    "Az egyetlen dolog, ami megbízhatatlanabb nálad, az az óvszer, amit apád használt.",
    "Ha retardáltnak nevezünk, az dicséret ahhoz képest, hogy milyen ostoba vagy.",
    "Nem tudtam, hogy a meghalás különleges képesség.",
    "Ha az egódtól az intelligenciád felé ugrottam volna, félúton éhen halnék.",
    "A tanulmányok azt mutatják, hogy a célzás nagyobb eséllyel találja el a célt.",
    "Hagynod kell játszani a székedet, legalább tudja, hogyan kell megtámasztani.",
    "Jelenleg körülbelül 37 billió sejt dolgozik együtt a testedben, és mindegyikük csalódást okoz.",
    "Eszköznek nevezném, de ez azt jelentené, hogy legalább egy szempontból hasznos voltál.",
    "Te vagy a részvételi díj emberi megfelelője.",
    "Szívesen látnám a dolgokat a te szemszögedből, de nem hiszem, hogy ennyire fel tudnám dugni a fejem a seggembe.",
    "Nem a szemétről beszélek, hanem a szeméttel beszélek",
    "A legenda szerint a 0-t először azután találták fel, hogy a tudósok kiszámították az esélyét, hogy valami hasznosat tegyen.",
    "Te olyan játékos vagy, aki 3. helyezést ér el egy 1-1 meccsen",
    "Nem azt mondom, hogy utállak, de kihúznám az életmentőjét, hogy feltöltsem a telefonomat.",
    "Te vagy a születésszabályozás ihletője.",
    "Féltékeny lesz valaha a segged arra a sok szarra, ami kijön a szádon",
    "Ki kellene kapcsolnia a játékot. Menjen ki, és keresse meg a legközelebbi fát, majd kérjen bocsánatot, amiért ennyi oxigént pazarol.",
    "Azt mondanám, hogy lőd le magad, de lefogadom, hogy kihagyod",
    "Tudtad, hogy a cápák évente csak 5 embert ölnek meg? Úgy tűnik, versenyed van",
    "Néhány babát a fejére ejtettek, de téged egyértelműen a falnak dobtak",
    "Melyik alapítványnak kell adakoznom, hogy segíthessek?",
    "Biztos vagyok benne, hogy a testpárnád nagyon büszke rád.",
    "Két rosszból nem lesz jó, vedd a szüleidet példaként.",
    "Lefogadom, hogy utoljára egy kfc vödörben érezted a mellet",
    "Talán Isten egy kicsit túl különlegessé tett téged.",
    "Lefogadom, hogy az agyad olyan jól érzi magát, mint az új, látva, hogy soha nem használod.",
    "Bizonyára nehéz lesz neked, egy mondatban kimeríted az egész szókincsedet.",
    "Néhány nagy golyó van rajtad. Kár, hogy azok a fickóé, aki hátulról kibaszott.",
    "Ha csak annyira üthetnél egy ellenséget, mint amennyit az apád üt.",
    "Meglepett, hogy meg tudtad nyomni a Telepítés gombot",
    "Néhány ember azért kap fizetést, hogy szopjon, te pedig ingyen csinálod.",
    "Megkérdezném, hány éves vagy, de tudom, hogy nem tudsz ennyit számolni.",
    "Rendben vagyok ezzel a csapattal. A városban dolgozom szemétszállítóként. Szoktam a szemetet hordani.",
    "Olyan sűrű vagy, mint egy tégla, de őszintén szólva kevésbé hasznos.",
    "Ráknak neveznélek, de a rák legalább megöl",
    "Ki állította passzívra a botokat?",
    "Te vagy az oka annak, hogy legalizálták az abortuszt"
}
local Swedish = {
    "Det enda som är lägre än ditt k/d-förhållande är ditt I.Q.",
    "Ditt mål är så dåligt att folk höll en insamling för det",
    "Bättre köp PC, sluta spela på skolbiblioteket",
    "Det enda som är mer opålitligt än du är kondomen som din pappa använde.",
    "Att kalla dig efterbliven är en komplimang i jämförelse med hur dum du faktiskt är.",
    "Jag visste inte att dö var en speciell förmåga.",
    "Om jag hoppade från ditt ego till din intelligens, skulle jag dö av svält halvvägs ner.",
    "Studier visar att sikte ger dig bättre chanser att nå ditt mål.",
    "Du borde låta din stol spela, åtminstone vet den hur den ska stödja.",
    "Det finns ungefär 37 biljoner celler som arbetar tillsammans i din kropp just nu, och du gör varenda en av dem besviken.",
    "Jag skulle kalla dig ett verktyg, men det skulle antyda att du var användbar på åtminstone ett sätt.",
    "Du är den mänskliga motsvarigheten till ett deltagandepris.",
    "Jag skulle älska att se saker ur ditt perspektiv, men jag tror inte att jag skulle kunna trycka huvudet så långt upp i rumpan.",
    "Jag pratar inte med papperskorgen, jag pratar med papperskorgen",
    "Legenden säger att siffran 0 först uppfanns efter att forskare beräknat din chans att göra något användbart.",
    "Du är den typen av spelare som får en 3:e plats i en 1v1-match",
    "Jag säger inte att jag hatar dig, men jag skulle koppla ur ditt livstöd för att ladda min telefon.",
    "Du är en inspiration för preventivmedel.",
    "Blir din röv någonsin avundsjuk på mängden skit som kommer ut ur din mun",
    "Du borde stänga av spelet. Gå bara ut och hitta närmaste träd och be det sedan om ursäkt för att du slösat så mycket syre.",
    "Jag skulle säga till dig att skjuta dig själv, men jag slår vad om att du missar",
    "Visste du att hajar bara dödar 5 personer varje år? Det verkar som om du har fått lite konkurrens",
    "Vissa bebisar tappades på huvudet men du kastades tydligt mot en vägg",
    "Till vilken stiftelse behöver jag donera för att hjälpa dig?",
    "Jag är säker på att din kroppskudde är väldigt stolt över dig.",
    "Två fel gör inte ett rätt, ta dina föräldrar som exempel.",
    "Jag slår vad om att senast du kände att ett bröst var i en kfc-hink",
    "Kanske Gud gjorde dig lite för speciell.",
    "Jag slår vad om att din hjärna känns lika bra som ny, eftersom du aldrig använder den.",
    "Det måste vara svårt för dig att uttömma hela ditt ordförråd i en mening.",
    "Du har några stora bollar på dig. Synd att de tillhör killen som knullar dig bakifrån.",
    "Om du bara kunde slå en fiende lika mycket som din pappa slår dig.",
    "Jag är förvånad över att du kunde trycka på Installera-knappen",
    "Vissa människor får betalt för att suga, du gör det gratis.",
    "Jag skulle fråga dig hur gammal du är men jag vet att du inte kan räkna så högt.",
    "Jag är okej med det här laget. Jag jobbar i staden som sophämtare. Jag är van vid att bära sopor.",
    "Du är tät som en tegelsten, men ärligt talat mindre användbar.",
    "Jag skulle kalla dig cancer, men cancer dödar åtminstone",
    "Vem har ställt in robotarna på passiva?",
    "Du är anledningen till att abort legaliserades"
}
local German = {
    "Du Hurensohn",
    "1 Du Hundesohn",
    "2 Du Hundesohn",
    "Ich fick deine Schwester"
}
local Anime = {
    "S-Sorry onii-chan p-please d-do me harder ;w;",
    "Y-You got me all wet now Senpai!",
    "D-Don't t-touch me there Senpai",
    "P-Please l-love me harder oniichan ohh grrh aahhhh~!",
    "Give me all your cum Senpai ahhhhh~",
    "F-Fuck me harder chan!",
    "Oh my god I hate you so much Senpai but please k-keep fucking me harder! ahhh~",
    "D-Do you like my stripped panties getting soaked by you and your hard cock? ehhh Master you're so lewd ^0^~",
    "Kun your cute little dick between my pussy lips looks really cute, I'm blushing",
    "M-Master does it feel good when I slide by tits up and down on your cute manly part?",
    "O-Oniichan my t-toes are so warm with your cum all over them uwu~",
    "Lets take this swimsuit off already <3 i'll drink your unknown melty juice",
    "S-Stop Senpai if we keep making these lewd sounds im going to cum~~",
    "You're such a pervert for filling me up with your baby batter Senpai~~",
    "Fill up my baby chamber with your semen kun ^-^",
    "M-Master d-dont spank my petite butt so hard ahhhH~~~ you're getting me so w-wet~",
    "Senpai your cock is already throbbing from my huge tits~",
    "Hey kun, Can I have some semen?",
    "M-My baby chamber is overflowing with your semen M-Master",
    "Y-Yes M-Master right there",
    "Oh do you wanna eat? Do you wanna take a bath? Or do you want me!",
    "it's not gay if you swallow the evidence S-Sempai",
    "Fill my throat pussy with your semen kun",
    "It-It's not gay if you're wearing thigh highs M-Master",
    "I-I need somewhere to blow my load. Can i borrow your bussy?",
    "A-ah shit... Y-your cock is big and in my ass already~?!",
    "I-I'm cumming, I'm cumming, CUM with me too!",
    "Drench me and I'll do the same!",
    "I'll swallow your sticky essence along with you~!",
    "You're my personal cum bucket!!",
    "B-baka please let me be your femboy sissy cum slut!",
    "That's a penis UwU you towd me you wewe a giww!!",
    "You are cordially invited to fuck my ass!",
    "Your resistance only makes my penis harder!",
    "Grab them, squeeze them, pinch them, pull them, lick them, bite them, suck them!",
    "It feels like his dick is sliding into a slimy pile of macaroni!",
    "Cum, you naughty cock! Do it! Do it! DO IT!!!",
    "Ahhhh... It's like a dream come true... I get to stick my dick inside Tatsuki Chan's ass...!",
    "This is the cock block police! Hold it right there!",
    "Y-You'll break M-my womb M-Master",
    "Ohoo, getting creampied made you cum? What a lewd bitch you are!",
    "I've jerked off every single day... Given birth to countless snails... All while fantasizing about the day I'd get to fuck you!",
    "You're looking at porn when you could be using your little sister instead!",
    "Umm... I don't wanna sound rude, but have you had a bath? Your panties look a bit yellow...",
    "H-hey, hey S-Sempai... W-wanna cuddle? UwU",
    "F-fuck my bussy M-Master!",
    "Hey, who wants a piece of this plump 19-year-old boy-pussy? Single file, boys, come get it while it's hot!",
    "Kouji-Kun, if you keep thrusting that hard, my boobs will fall off!",
    "Papa you liar! How could you say that while having such a HUGE erection.",
    "I-I just wanna borrow y-your dick...",
    "Hehe don't touch me there Onii-chann UwU",
    "Your cum is all over my wet clit M-Master",
    "It Feels like you're pounding me with the force of a thousand suns Senpai",
    "I like when Y-you fill me with your baby water S-Senpai",
    "Y-yes right there S-Sempai hooyah",
    "P-please keep filling my baby chamber S-Sempai",
    "O-Onii-chan it felt so good when you punded my bussy",
    "P-please Onii-chan keep filling my baby chamber with your melty juice",
    "O-Onii-chan you just one shot my baby chamber",
    "I-Im nothing but a F-fucktoy slut for your M-monster fuckmeat!",
    "Dominate my ovaries with your vicious swimmers!",
    "Impregnate me with your viral stud genes!",
    "M-My body yearns for your sweet dick milk",
    "Y-Your meat septer has penetrated my tight boy hole",
    "M-My nipples are being tantalized",
    "Mnn FASTER... HARDER! Turn me into your femboy slut~!",
    "Penetrate me until I bust!",
    "Mmmm- soothe me, caress me, Fuck me, breed me!",
    "Probe your thick, wet, throbbing cock deeper and deeper into my boipussy~!!",
    "I'm your personal cum bucket!!",
    "Hya! Not my ears! Ah... It tickles! Ah!",
    "Can you really blame me for getting a boner after seeing that?",
    "The two of us will cover my sis with our cum!",
    "Kouta... I can't believe how BIG his... Wait! Forget about that!! Is Nyuu-chan really giving him a Tit-Fuck!?",
    "Senpai shove deeper your penis in m-my pussy (>ω<) please",
    "This... This is almost like... like somehow I'm the one raping him!",
    "I'm coming fwom you fwuking my asshole mmyyy!",
    "Boys just can't consider themselves an adult... Until they've had a chance to cum with a girl's ampit.",
    "P-Please be gentle, Goku-Senpai!",
    "We're both gonna fuck your pussy at the same time!"
}


local kys = gui.add_combo("Killsay", "lua>tab a", {"Off","English","Russian","German","Swedish","Hungarian","Bulgarian","Polish","Spanish","Arabic","Anime"})

function on_player_death(event)
    local attacker = engine.get_player_for_user_id(event:get_int('attacker'));
    local userid = engine.get_player_for_user_id(event:get_int('userid'));
    local userInfo = engine.get_player_info(userid);
    local lp = engine.get_local_player();
    if attacker == lp and userid ~= lp then
        if kys:get_int() == 1 then
            engine.exec("say " .. English[utils.random_int(1, #English)])
        elseif kys:get_int() == 2 then
            engine.exec("say " .. Russian[utils.random_int(1, #Russian)])
        elseif kys:get_int() == 3 then
            engine.exec("say " .. German[utils.random_int(1, #German)])
        elseif kys:get_int() == 4 then
            engine.exec("say " .. Swedish[utils.random_int(1, #Swedish)])
        elseif kys:get_int() == 5 then
            engine.exec("say " .. Hungarian[utils.random_int(1, #Hungarian)])
        elseif kys:get_int() == 6 then
            engine.exec("say " .. Bulgarian[utils.random_int(1, #Bulgarian)])
        elseif kys:get_int() == 7 then
            engine.exec("say " .. Polish[utils.random_int(1, #Polish)])
        elseif kys:get_int() == 8 then
            engine.exec("say " .. Spanish[utils.random_int(1, #Spanish)])
        elseif kys:get_int() == 9 then
            engine.exec("say " .. Arabic[utils.random_int(1, #Arabic)])
        elseif kys:get_int() == 10 then
            engine.exec("say " .. Anime[utils.random_int(1, #Anime)])                                                                        
        end
    end
end