--You have my permission to use this script anywhere and for anything pasting etc. Credit needs to be included!
local clantag_main = gui.add_combo("Clantags", "Lua>Tab A", {"OFF","MonkeySquad","BosniaHook","Ev0lve","Primordial","RaweTrip","Neverlose","Gamesense","Skeet.cc","Nemesis","Onetap.su","Monolith","Airflow","PlagueCheat","xixurHVH","SpiritHack","Legendware","Nixware","Aimware","Weave","Rifk"})
local main_MonkeySquad = {
    ">",
    ">M",
    ">Mo",
    ">Mon",
    ">Monk",
    ">Monke",
    ">Monkey",
    ">Monkey",
    ">MonkeyS",
    ">MonkeySq",
    ">MonkeySqu",
    ">MonkeySqua",
    ">MonkeySquad",
    "MonkeySquad",
    "$onkeySquad",
    "M$nkeySquad",
    "Mo$keySquad",
    "Mon$eySquad",
    "Monk$ySquad",
    "Monke$Squad",
    "Monkey$quad",
    "MonkeyS$uad",
    "MonkeySq$ad",
    "MonkeySqu$d",
    "MonkeySqua$",
    "MonkeySquad",
    "MonkeySqua<",
    "MonkeySqu<",
    "MonkeySq<",
    "MonkeyS<",
    "Monkey<",
    "Monke<",
    "Monk<",
    "Mon<",
    "Mo<",
    "M<",
    "<",
}
local main_BosniaHook = {
    "☂",
    "☂B",
    "☂Bo",
    "☂Bos",
    "☂Bosn",
    "☂Bosni",
    "☂Bosnia",
    "☂BosniaH",
    "☂BosniaHo",
    "☂BosniaHoo",
    "☂BosniaHook",
    "B☂osniaHook",
    "Bo☂sniaHook",
    "Bos☂niaHook",
    "Bosn☂iaHook",
    "Bosni☂aHook",                    
    "Bosnia☂Hook",
    "BosniaH☂ook",
    "BosniaHo☂ok",
    "BosniaHoo☂k",
    "BosniaHook☂",
    "BosniaHook",        
    "BosniaHook",
    "BosniaHook",
    "_osniaHoo_",
    "__sniaHo__",
    "___niaH___",
    "____ia____",
    "__________",
    "_____",
    "__",  
    "_",
    "",             
    "☂",
}
local main_ev0lve = {
    "           ",
    "         e" ,
    "        ev" ,
    "       ev0" ,
    "      ev0l" ,
    "     ev0lv" ,
    "    ev0lve" ,
    "   ev0lve." ,
    "  ev0lve.x ",
    " ev0lve.xy ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " v0lve.xyz " ,
    " 0lve.xyz ",
    " lve.xyz ",
    "ve.xyz   ",
    "e.xyz    ",
    ".xyz     ",
    "xyz      ",
    "yz       ",
    "z        ",
}
local main_primordial = {
    " ⌛ ",
    " ⌛ ",
    " ⌛ ",
    " ⌛ primo ",
    " ⌛ primor ",
    " ⌛ primord ",
    " ⌛ primordi ",
    " ⌛ primordia ",
    " ⌛ primordial ",
    " ⌛ primordial ",
    " ⌛ primordial ",
    " ⌛ primordial ",
    " ⌛ primordia ",
    " ⌛ primordi ",
    " ⌛ primord ",
    " ⌛ primor ",
    " ⌛ primo ",
    " ⌛ prim ",
    " ⌛ pri ",
    " ⌛ pr ",
    " ⌛ p",
    " ⌛  ",
}
local main_Rawetrip = {
    " 〄 " ,
    " R>|〄 " ,
    " RA>|〄 " ,
    " R4W>|〄 " ,
    " RAWЭ>|〄 " ,
    " R4W3T>|〄 " ,
    " RAWΣTR>|〄 " ,
    " Я4WETRI>|〄 " ,
    " RAWETRIP>|〄 " ,
    " RAWETRIP<|〄 " ,
    " R4WETRI<|〄 " ,
    " RAWΣTR<|〄 " ,
    " R4W3T<|〄 " ,
    " RAWЭ<|〄 " ,
    " R4W<|〄 " ,
    " RA<|〄 " ,
    " R<|〄 " ,
    " 〄 " ,
}
local main_Neverlose = {
    " ",
    "N ",
    "N3 ",
    "Ne ",
    "Ne\\ ",
    "Ne\\/ ",
    "Nev ",
    "Nev3 ",
    "Neve ",
    "Neve| ",
    "Neve|2 ",
    "Never| ",
    "Never|_ ",
    "Neverl ",
    "Neverl0 ",
    "Neverlo ",
    "Neverlo5 ",
    "Neverlos ",
    "Neverlos3 ",
    "Neverlose ",
    "Neverlose. ",
    "Neverlose.< ",
    "Neverlose.c< ",
    "Neverlose.cc ",
    "Neverlose.c< ",
    "Neverlose.< ",
    "Neverlose. ",
    "Neverlose ",
    "Neverlos3 ",
    "Neverlos ",
    "Neverlo_ ",
    "Neverlo5 ",
    "Neverlo ",
    "Neverl_ ",
    "Never|0 ",
    "Never| ",
    "Neve|2 ",
    "Neve| ",
    "Neve ",
    "Nev3 ",
    "Nev ",
    "Ne\\/ ",
    "Ne\\ ",
    "Ne ",
    "N3 ",
    "N ",
    "|\\| ",
} 
local main_Gamesense = {
    "ga",
    "gam",
    "game",
    "games",
    "gamese",
    "gamesen",
    "gamesens",
    "gamesense",
    "gamesense ",
    "gamesense ",
    "gamesense ",
    "gamesense ",
    "gamesense ",
    "gamesense ",
    "gamesense ",
    "gamesense ",
    "gamesense ",
    "gamesense ",
    "gamesense ",
    "gamesense ",
    "amesense ",
    "mesense ",
    "esense ",
    "sense ",
    "ense ",
    "nse ",
    "se ",
    "e ",
    "",
}
local main_Nemesis = {
    "nemesis",
    "n3m3sis",
    "nemesis",
    "n3m3sis",
    "nemesis",
    "n3m3sis",
    "nemesis",
    "n3m3sis",
}
local main_Onetapsu = {
    "onetap.su",
    "nepat.su o",
    "epat.su on",
    "pat.su one",
    "ap.su onet",
    "t.su oneta",
    ".su onetap",
    "su onetap.",
    "u onetap.s",
    "onetap.su",
}
local main_Monolith = {
    "[M-------] ",
    "[Mo------] ",
    "[Mon-----] ",
    "[Mono----] ",
    "[Mono----] ",
    "[Monol---] ",
    "[Monoli--] ",
    "[Monolit-] ",
    "[Monolith] ",
    "[Monolit-] ",
    "[Monoli--] ",
    "[Monol---] ",
    "[Mono----] ",
    "[Mon-----] ",
    "[Mo------] ",
    "[M-------] ",
    "[--------] ",
    "[-------<] ",
    "[------<8] ",
    "[-----<8>] ",
    "[----<8>-] ",
    "[---<8>--] ",
    "[--<8>---] ",
    "[-<8>----] ",
    "[<8>-----] ",
    "[8>------] ",
    "[>-------] ",
    "[--------] ",
}
local main_plague = {
    "plaguecheat"
}
local main_xixurHVH = {
    "◇〄⌛☂xixurHVH☂⌛〄◇"
}
local main_airflow = {
    "a",
    "ai",
    "air",
    "airf",
    "airfl",
    "airflo",
    "airflow",
    "airflow.",
    "airflow.s",
    "airflow.su",
    "airflow.su",
    "airflow.s",
    "airflow.",
    "airflow",
    "airflo",
    "airfl",
    "airf",
    "air",
    "ai",
    "a",
    " "
}
local main_SpiritHack = {
    "◇ ",
    "◇ ",
    "◇ s",
    "◇ sp",
    "◇ spi",
    "◇ spir",
    "◇ spirt",
    "◇ spirth",
    "◇ spirtha",
    "◇ spirthac",
    "◇ spirthack",
    "◇ spirthack",
    "◇ spirthac",
    "◇ spirtha",
    "◇ spirth",
    "◇ spirt",
    "◇ spir",
    "◇ spi",
    "◇ sp",
    "◇ s",
    "◇ ",
    "◇ ",
}
local main_nixware = {
    "n",
    "ni",
    "nix",
    "nixw",
    "nixwa",
    "nixwar",
    "nixware",
    "nixware.",
    "nixware.c",
    "nixware.cc",
    "nixware.cc",
    "nixware.cc",
    "nixware.c",
    "nixware.",
    "nixware",
    "nixwar",
    "nixwa",
    "nixw",
    "nix",
    "ni",
    "n",
}
local main_aimware = {
    "AIMWARE.net",
    "t AIMWARE.ne",
    "et AIMWARE.n",
    ".net AIMWARE",
    "E.net AIMWAR",
    "RE.net AIMWA",
    "ARE.net    AIMW",
    "WARE.net AIM",
    "MWARE.net AI",
    "IMWARE.net A",
    "AIMWARE.net",
    "AIMWARE.net",
}
local main_weave = {  
    "w",
    "we",
    "wea",
    "weav",
    "weave",
    "w3av3",
    "we4ve",
    "weave",
    "weav",
    "wea",
    "we",
    "w",
    "",
}
local main_rifk = {
    " [ ] ",
    " [ R ] ",
    " [ Ri ] ",
    " [ Rif ] " ,
    " [ Rifk ' ] ",
    " [ Rifk ' ] ",
    " [ Rifk ' ] ",
    " [ Rifk ] ",
    " [ Rif ] ",
    " [ Ri ] ",
    " [ R ] ",
    " [ ] ",
}
local main_legendware = {
    "l ",
    "le ",
    "leg ",
    "lege ",
    "legen ",
    "legend ",
    "legendw ",
    "legendwa ",
    "legendwar ",
    "legendware ",
    "legendware ",
    "legendwar ",
    "legendwa ",
    "legendw ",
    "legend ",
    "legen " ,
    "lege ",
    "leg ",
    "le ",
    "l ",
}
local main_millionware = {
    "$ millionware ",
    "$ e millionwar",
    "$ re millionwa",
    "$ are millionw",
    "$ ware million",
    "$ nware millio",
    "$ onware milli",
    "$ ionware mill",
    "$ lionware mil",
    "$ llionware mi",
    "$ illionware m",
    "$ millionware" ,
}
local main_skeetcc = {
    "s",
    "ske",
    "skee",
    "skeet",
    "skeet.",
    "skeet.c",
    "skeet.cc",
    "skeet.cc ",
    "skeet.cc ",
    "skeet.cc ",
    "skeet.cc ",
    "skeet.cc ",
    "skeet.cc ",
    "skeet.cc ",
    "skeet.cc ",
    "skeet.cc ",
    "skeet.cc ",
    "keet.cc ",
    "eet.cc ",
    "et.cc ",
    "t.cc ",
    ".cc",
    "cc",
    "c",
    "",
}
local main_nineelevel = {
    "✈__▮_▮ ",
    "_✈_▮_▮",
    "__✈▮_▮",
    "___☠✈▮",
    "___☠_☠ ",
}


local tags = 
{
    main_MonkeySquad,
    main_BosniaHook,
    main_ev0lve,
    main_primordial,
    main_Rawetrip,
    main_Neverlose,
    main_Gamesense,
    main_skeetcc,
    main_Nemesis,
    main_Onetapsu,
    main_Monolith,
    main_airflow,
    main_plague,
    main_xixurHVH,
    main_SpiritHack,
    main_legendware,
    main_nixware,
    main_aimware,
    main_weave,
    main_rifk,
}

local defaultct = gui.get_config_item("misc>various>clan tag") 
local old_tag_string   = nil
local can_reset = false
function on_paint()

    local tag_idx = clantag_main:get_int()
    local tag = tags[tag_idx]
    if tag then
        local curtime = math.floor((global_vars.curtime) * 2.5)
        local tag_string = tag[curtime % #tag + 1]
        if tag_string ~= old_tag_string then
            utils.set_clan_tag(tag_string)
            defaultct:set_bool(false)
            old_tag_string = tag_string
            can_reset = true
        end
    else
        if can_reset then
            utils.set_clan_tag(" ") 
            can_reset = false
        end
    end
end
